export const contactsData = [
    {
      id: '1',
      firstName: 'John',
      lastName: 'Doe',
      phoneNumber: '+33 6 12 34 56 78',
      status: 'Online',
    },
    {
      id: '2',
      firstName: 'Jane',
      lastName: 'Smith',
      phoneNumber: '+33 6 98 76 54 32',
      status: 'Offline',
    },
    {
      id: '3',
      firstName: 'Paul',
      lastName: 'Dupont',
      phoneNumber: '+33 6 23 45 67 89',
      status: 'Online',
    },
    {
      id: '4',
      firstName: 'Claire',
      lastName: 'Martin',
      phoneNumber: '+33 6 34 56 78 90',
      status: 'Offline',
    },
    {
      id: '5',
      firstName: 'Lucas',
      lastName: 'Bernard',
      phoneNumber: '+33 6 78 90 12 34',
      status: 'Online',
    },
    {
      id: '6',
      firstName: 'Sophie',
      lastName: 'Girard',
      phoneNumber: '+33 6 45 67 89 01',
      status: 'Offline',
    },
    {
      id: '7',
      firstName: 'Antoine',
      lastName: 'Lefevre',
      phoneNumber: '+33 6 56 78 90 12',
      status: 'Online',
    },
    {
      id: '8',
      firstName: 'Nathalie',
      lastName: 'Moreau',
      phoneNumber: '+33 6 67 89 01 23',
      status: 'Offline',
    },
    {
      id: '9',
      firstName: 'Thomas',
      lastName: 'Blanc',
      phoneNumber: '+33 6 78 01 23 45',
      status: 'Online',
    },
    {
      id: '10',
      firstName: 'Julie',
      lastName: 'Fontaine',
      phoneNumber: '+33 6 89 01 23 45',
      status: 'Offline',
    },
    {
      id: '11',
      firstName: 'Mathieu',
      lastName: 'Roche',
      phoneNumber: '+33 6 12 34 56 89',
      status: 'Online',
    },
    {
      id: '12',
      firstName: 'Elodie',
      lastName: 'Marchand',
      phoneNumber: '+33 6 23 45 67 90',
      status: 'Offline',
    },
    {
      id: '13',
      firstName: 'Guillaume',
      lastName: 'Renard',
      phoneNumber: '+33 6 34 56 78 01',
      status: 'Online',
    },
    {
      id: '14',
      firstName: 'Isabelle',
      lastName: 'Lemoine',
      phoneNumber: '+33 6 45 67 89 12',
      status: 'Offline',
    },
    {
      id: '15',
      firstName: 'Alexandre',
      lastName: 'Faure',
      phoneNumber: '+33 6 56 78 90 23',
      status: 'Online',
    },
    {
      id: '16',
      firstName: 'Marie',
      lastName: 'Dubois',
      phoneNumber: '+33 6 67 89 01 34',
      status: 'Offline',
    },
    {
      id: '17',
      firstName: 'Cédric',
      lastName: 'Moulin',
      phoneNumber: '+33 6 78 01 23 56',
      status: 'Online',
    },
    {
      id: '18',
      firstName: 'Laure',
      lastName: 'Clement',
      phoneNumber: '+33 6 89 01 23 67',
      status: 'Offline',
    },
    {
      id: '19',
      firstName: 'François',
      lastName: 'Garnier',
      phoneNumber: '+33 6 12 34 56 78',
      status: 'Online',
    },
    {
      id: '20',
      firstName: 'Caroline',
      lastName: 'Benoit',
      phoneNumber: '+33 6 23 45 67 89',
      status: 'Offline',
    },
    {
      id: '21',
      firstName: 'Vincent',
      lastName: 'Perrin',
      phoneNumber: '+33 6 34 56 78 90',
      status: 'Online',
    },
    {
      id: '22',
      firstName: 'Amélie',
      lastName: 'Morin',
      phoneNumber: '+33 6 45 67 89 01',
      status: 'Offline',
    },
    {
      id: '23',
      firstName: 'Xavier',
      lastName: 'Roux',
      phoneNumber: '+33 6 56 78 90 12',
      status: 'Online',
    },
    {
      id: '24',
      firstName: 'Hélène',
      lastName: 'Dumas',
      phoneNumber: '+33 6 67 89 01 23',
      status: 'Offline',
    },
    {
      id: '25',
      firstName: 'Yannick',
      lastName: 'Masson',
      phoneNumber: '+33 6 78 01 23 45',
      status: 'Online',
    },
    {
      id: '26',
      firstName: 'Audrey',
      lastName: 'Brun',
      phoneNumber: '+33 6 89 01 23 45',
      status: 'Offline',
    },
    {
      id: '27',
      firstName: 'Benoît',
      lastName: 'Jacques',
      phoneNumber: '+33 6 12 34 56 89',
      status: 'Online',
    },
    {
      id: '28',
      firstName: 'Camille',
      lastName: 'Roy',
      phoneNumber: '+33 6 23 45 67 90',
      status: 'Offline',
    },
    {
      id: '29',
      firstName: 'Didier',
      lastName: 'Gerard',
      phoneNumber: '+33 6 34 56 78 01',
      status: 'Online',
    },
    {
      id: '30',
      firstName: 'Emilie',
      lastName: 'Giraud',
      phoneNumber: '+33 6 45 67 89 12',
      status: 'Offline',
    },
  ];
  